[build-system]
requires = ["flit_core >=3.2,<4","myst_parser"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Benoit Tallandier", email = "btallandier@linagora.com"}]
dynamic = ["version", "description"]
